# Generated by Django 5.0 on 2023-12-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("martial_arts_register", "0002_martialart_country_of_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="martialart",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
