# Generated by Django 5.0 on 2023-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("martial_arts_register", "0004_motherland_alter_martialart_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="motherland",
            old_name="region",
            new_name="capital",
        ),
        migrations.RemoveField(
            model_name="motherland",
            name="founder",
        ),
        migrations.AddField(
            model_name="motherland",
            name="continent",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="motherland",
            name="official_language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
