# Generated by Django 5.0 on 2023-12-13 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("martial_arts_register", "0005_rename_region_motherland_capital_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="martialart",
            name="country_of_origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="martial_arts",
                to="martial_arts_register.motherland",
            ),
        ),
    ]
