# Generated by Django 5.0 on 2023-12-15 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("martial_arts_register", "0007_artist_motherland_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="birth_year",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MaxValueValidator(2023)]
            ),
        ),
    ]
