# Generated by Django 5.0 on 2023-12-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("martial_arts_register", "0008_artist_birth_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Embodyment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("event_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cultural_practice_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tradition_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="artist",
            options={"verbose_name_plural": "Martial artists"},
        ),
        migrations.RemoveField(
            model_name="motherland",
            name="artist",
        ),
        migrations.AddField(
            model_name="motherland",
            name="embodyment",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="martial_arts_register.embodyment",
            ),
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("power_generation", models.CharField(max_length=50)),
                ("skill_level", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "effective_range",
                    models.CharField(
                        choices=[
                            ("close", "Close"),
                            ("middle", "Middle"),
                            ("long", "Long"),
                        ],
                        default="middle",
                        max_length=10,
                    ),
                ),
                (
                    "originating_martial_art",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="techniques",
                        to="martial_arts_register.martialart",
                    ),
                ),
            ],
        ),
    ]
