# Generated by Django 5.0 on 2023-12-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "martial_arts_register",
            "0010_artist_fav_technique_martialart_techniques_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="martialart",
            name="techniques",
            field=models.ManyToManyField(
                blank=True, null=True, to="martial_arts_register.technique"
            ),
        ),
    ]
