# Generated by Django 5.0 on 2023-12-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("martial_arts_register", "0011_alter_martialart_techniques"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Professional", "Professional"),
                ],
                default="Intermediate",
                max_length=20,
            ),
        ),
    ]
